FORMAT: 1A

# Chatbot Backend API

Design for Chatbot back end for demo session

## Fixtures Collection [/fixtures]
A list of upcoming fixtures

### List All Fixtures [GET]

+ Response 200 (application/json)

        [
            {
            "self": 1,
            "date": "2017-07-12",
            "time": "8pm",
            "opposition": "Rising Pune Supergiants"
            },
            
            {
            "id": 2,
            "date": "2017-07-14",
            "time": "8pm",
            "opposition": "Royal Challengers Bangalore"
            },
        ]


## Packages Collection [/fixtures/{id}/packages]
Seating and offer packages

+ Parameters
    + id - Fixture that the packages are offered for

### List All Packages [GET]

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "section": "Section 115",
                "row": "3",
                "available": true,
                "price": 299,
                "link": {
                    "rel": "image",
                    "href": "https://publicdocs-corp.documents.us2.oraclecloud.com/documents/link/LF7206C60A9212DA72124CA9F6C3FF17C1177E4725F3/file/D2BA28E8C506DC0CDA4F9C14F6C3FF17C1177E4725F3?allowInterrupt=1"
                }
            },
            {
                "id": 2,
                "section": "Section 216",
                "row": "7",
                "available": true,
                "price": 219,
                "link": {
                    "rel": "image",
                    "href": "https://publicdocs-corp.documents.us2.oraclecloud.com/documents/link/LF7206C60A9212DA72124CA9F6C3FF17C1177E4725F3/file/D2BA28E8C506DC0CDA4F9C14F6C3FF17C1177E4725F3?allowInterrupt=1"
                }
            },
            {
                "section": "Section 229",
                "row": "12",
                "available": true,
                "price": 146,
                "link": {
                    "rel": "image",
                    "href": "https://publicdocs-corp.documents.us2.oraclecloud.com/documents/link/LF7206C60A9212DA72124CA9F6C3FF17C1177E4725F3/file/DF03AD812F69F02A82C04FC2F6C3FF17C1177E4725F3?allowInterrupt=1"
                }
            }
        ]

## Details Collection [/fixtures/{fixtureId}/packages/{packageId}]
Details for a given package


+ Parameters
    + fixtureId - Fixture that the packages are offered for
    + packageId - Package that the details belong to


### Retrieve Details [GET]

+ Response 200 (application/json)

        {
            "name": "Guiness",
            "description": "No preservatives or additives. 100% natural, ingredients create a unique flavour",
            "link": {
                "rel": "image",
                "href": "https://publicdocs-corp.documents.us2.oraclecloud.com/documents/link/LF7206C60A9212DA72124CA9F6C3FF17C1177E4725F3/file/D2680B911AEB03B8C3B6EF22F6C3FF17C1177E4725F3?dRevLabel=LATEST&allowInterrupt=1"
            }
        }

## Bookings Collection [/bookings]

### Purchase a Ticket [POST]

+ Request (application/json)

        {
            "fixture": 1,
            "package": 2
        }

+ Response 200 (application/json)

        {
            "status": 0,
            "url": "/bookings/1"
        }