FORMAT: 1A

# Chatbot Backend API

Design for Chatbot back end for demo

## Seats Collection [/seats]
Game seats

### List All Seats [GET]

Lists all seats and availability

+ Response 200 (application/json)

        [
            {
                "section": "A",
                "number": "1",
                "available": true,
                "price": 0,
                "link": {
                    "rel": "image",
                    "href": "http://my.link.tld/image.png"
                }
            },
            {
                "section": "A",
                "number": "2",
                "available": true,
                "price": 0,
                "link": {
                    "rel": "image",
                    "href": "http://my.link.tld/image.png"
                }
            },
            {
                "section": "A",
                "number": "3",
                "available": true,
                "price": 0,
                "link": {
                    "rel": "image",
                    "href": "http://my.link.tld/image.png"
                }
            },
            {
                "section": "A",
                "number": "4",
                "available": true,
                "price": 0,
                "link": {
                    "rel": "image",
                    "href": "http://my.link.tld/image.png"
                }
            }
        ]

## Beers Collection [/beers]
Available beers

### List All Beers [GET]

Lists all available beers on offer

+ Response 200 (application/json)

        [
            {
                "name": "Pilsner Urquell",
                "link": {
                    "rel": "image",
                    "href": "http://my.link.tld/image.png"
                }
            },
            {
                "name": "Fat Tire",
                "link": {
                    "rel": "image",
                    "href": "http://my.link.tld/image.png"
                }
            },
            {
                "name": "Guiness",
                "link": {
                    "rel": "image",
                    "href": "http://my.link.tld/image.png"
                }
            },
            {
                "name": "Beer4",
                "link": {
                    "rel": "image",
                    "href": "http://my.link.tld/image.png"
                }
            }
        ]